# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=300)),
                ('categoryid', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sf_bannerurl',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('truckid', models.CharField(max_length=100)),
                ('original', models.DecimalField(decimal_places=1, max_digits=5)),
                ('present', models.DecimalField(decimal_places=1, max_digits=5)),
                ('categoryid', models.CharField(max_length=100)),
                ('childid', models.CharField(max_length=100)),
                ('childname', models.CharField(max_length=200)),
                ('dealerid', models.CharField(max_length=100)),
                ('hot', models.IntegerField()),
                ('new', models.IntegerField()),
            ],
            options={
                'db_table': 'sf_goods',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'sf_wheel',
            },
        ),
    ]
